/**
 * Migration v149 (upstream facts_kind_idea_alter) — F5.
 * Upstream assigned v145; the downstream source-event ledger already owns
 * v145-v148, so this upgrade must run once after that history.
 *
 * Widens the facts.kind CHECK with 'idea'. The constraint shipped INLINE in
 * v45's CREATE TABLE, so Postgres autogenerated its name (facts_kind_check)
 * and pre-v149 brains carry the 5-kind predicate: an INSERT with kind='idea'
 * violates it. v149 probes pg_constraint for the autogen name, drops it if
 * present, and re-adds the widened CHECK under the same deterministic name
 * (the v47 facts_notability_alter alter-counterpart pattern).
 *
 * Pinned contracts:
 * 1. v149 exists with the canonical name, idempotent flag, and a sql block
 *    carrying the probe + the widened 6-kind predicate.
 * 2. Fresh init: the facts kind CHECK admits 'idea'; an INSERT succeeds.
 * 3. Upgrade: on a brain restored to the pre-v149 5-kind CHECK (positive
 *    control: kind='idea' verifiably rejected), a ledger rewind to 148 →
 *    runMigrations swaps the constraint, the INSERT succeeds, re-run applies
 *    nothing, and re-executing the v149 SQL directly converges (drop+re-add
 *    of an identical predicate — exactly one constraint row remains).
 */

import { describe, test, expect, beforeAll, afterAll } from 'bun:test';
import { PGLiteEngine } from '../src/core/pglite-engine.ts';
import { MIGRATIONS, LATEST_VERSION, runMigrations } from '../src/core/migrate.ts';

let engine: PGLiteEngine;

const V149_SQL = MIGRATIONS.find(m => m.version === 149)?.sql ?? '';
const WIDENED_LIST = "'event','preference','commitment','belief','fact','idea'";
const NARROW_LIST = "'event','preference','commitment','belief','fact'";

beforeAll(async () => {
  engine = new PGLiteEngine();
  await engine.connect({ database_url: '' }); // in-memory
  await engine.initSchema();
}, 60_000);

afterAll(async () => {
  await engine.disconnect();
});

/** All facts_kind_check constraint definitions currently on facts. */
async function kindCheckDefs(): Promise<string[]> {
  const rows = await engine.executeRaw<{ def: string }>(
    `SELECT pg_get_constraintdef(oid) AS def FROM pg_constraint
      WHERE conname = 'facts_kind_check' AND conrelid = 'facts'::regclass`,
  );
  return rows.map(r => r.def);
}

async function insertIdeaFact(fact: string): Promise<void> {
  await engine.executeRaw(
    `INSERT INTO facts (fact, kind, source) VALUES ($1, 'idea', 'test:v149')`,
    [fact],
  );
}

describe('migration v149 — structure', () => {
  test('exists with canonical name, idempotent flag, probe + widened predicate', () => {
    const v149 = MIGRATIONS.find(m => m.version === 149);
    expect(v149).toBeDefined();
    expect(v149?.name).toBe('upstream_facts_kind_idea_alter');
    expect(v149?.idempotent).toBe(true);
    expect(V149_SQL).toContain(`conname = 'facts_kind_check'`);
    expect(V149_SQL).toContain('DROP CONSTRAINT facts_kind_check');
    expect(V149_SQL).toContain(`CHECK (kind IN (${WIDENED_LIST}))`);
    expect(LATEST_VERSION).toBeGreaterThanOrEqual(149);
  });
});

describe('migration v149 — fresh init (PGLite)', () => {
  test("fresh schema's kind CHECK admits 'idea'; INSERT succeeds", async () => {
    const defs = await kindCheckDefs();
    expect(defs).toHaveLength(1);
    expect(defs[0]).toContain('idea');

    await insertIdeaFact('fresh-init idea row');
    const rows = await engine.executeRaw<{ kind: string }>(
      `SELECT kind FROM facts WHERE fact = 'fresh-init idea row'`,
    );
    expect(rows.map(r => r.kind)).toEqual(['idea']);
  });
});

describe('migration v149 — upgrade from a pre-v149 brain (PGLite)', () => {
  test('swaps the 5-kind constraint for the widened one; re-run applies nothing', async () => {
    // Simulate a pre-v149 brain: clear idea rows (they'd violate the narrow
    // CHECK on re-add), then restore the 5-kind constraint under the autogen
    // name v45's inline DDL produced.
    await engine.executeRaw(`DELETE FROM facts WHERE kind = 'idea'`);
    await engine.executeRaw('ALTER TABLE facts DROP CONSTRAINT IF EXISTS facts_kind_check');
    await engine.executeRaw(
      `ALTER TABLE facts ADD CONSTRAINT facts_kind_check CHECK (kind IN (${NARROW_LIST}))`,
    );

    // Positive control: the pre-v149 shape verifiably rejects kind='idea'.
    await expect(insertIdeaFact('blocked idea row')).rejects.toThrow();

    // Apply v149 via the real migration runner (ledger rewind below 149).
    // Keep a populated downstream receipt: upgrading the upstream facts kind
    // must not recreate, clear, or reinterpret the source-event history.
    await engine.executeRaw(`
      INSERT INTO source_event_receipts
        (source_id,event_key,source_kind,source_key,source_uri,source_slug,
         content_hash,processor_version,observed_at,event_date,status,
         event_id,revision_id,artifact_slug,projection_state)
      VALUES ('default','upgrade-sentinel','email','fixture:1','fixture://1',
        'raw/fixture/1','fixture-hash','fixture-v1',now(),'2026-01-01',
        'partial','fixture-event','fixture-revision','source-events/fixture',
        'committed')
    `);
    const before = await engine.executeRaw(
      `SELECT * FROM source_event_receipts WHERE event_key='upgrade-sentinel'`,
    );
    await engine.setConfig('version', '148');
    const res = await runMigrations(engine);
    expect(res.applied).toBe(1);
    expect(await engine.getConfig('version')).toBe(String(LATEST_VERSION));
    expect(await engine.executeRaw(
      `SELECT * FROM source_event_receipts WHERE event_key='upgrade-sentinel'`,
    )).toEqual(before);

    const defs = await kindCheckDefs();
    expect(defs).toHaveLength(1);
    expect(defs[0]).toContain('idea');
    await insertIdeaFact('post-upgrade idea row');

    // Ledger idempotency: re-run applies nothing.
    const rerun = await runMigrations(engine);
    expect(rerun.applied).toBe(0);

    // SQL-level idempotency: re-executing the v149 block on an up-to-date
    // brain converges (conditional drop + re-add of the identical predicate)
    // — no error, still exactly one constraint, still widened.
    await engine.runMigration(149, V149_SQL);
    const after = await kindCheckDefs();
    expect(after).toHaveLength(1);
    expect(after[0]).toContain('idea');
    await insertIdeaFact('post-rerun idea row');
  });
});
